---
title: "Overview"
output:
  html_document:
    theme: cosmo
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The Disease Modeling Workshop will start with knowledge sharing by each of our facilitators. Then, in the afternoon, each participants will have a chance to give a short presentation about themselves, their current project that they are working on, and their aspirations from this workshop. At the end of the first day, the participants will decide to which problems they will work on for their mini-projects.

On the second day, we will start with an introductory lecture on disease modeling specifically on the formulation of the Susceptible-Infected- Recovered (SIR) Model that describes the spread of an infectious disease. Discussion on the Basic Reproduction Number, R0, will also be included. The model is in the form of a mathematical equations (to be specific, it is a system of differential equations). We presume that the participants have basic calculus knowledge. Then, we will move to “SIR Modeling in R” session that discusses on how to solve the SIR Model using R programming. The next session will be on the analysis of the solution obtained from the model. Basically describing what we can do with the solution obtained to make decision on control measures. Time-Series Analysis will be introduced based on collected disease data. The participants will also learn about trend, periodicity and seasonality.

On the third and fourth day, the participants will go into their groups and work on mini projects, which the facilitators help to define, based on the data provided by the participants. During these two days, few walk-through tutorials on SIR, R0, and time-series forecasting will also be conducted by the facilitators.

On the final day, the participants will present their mini projects and obtain constructive feedback from the facilitators. Before we end the workshop, we will convene into roundtable discussion on specific issues brought by the participants and facilitators which regards to Disease Modeling activities in Malaysia.